#!/usr/bin/env bash
# Regenerate src/spec.ts from a mainspring-contracts release.
# Downloads the release Wasm, checks it against the release SHA256SUMS,
# and embeds each contract's interface so the SDK needs no network fetch.
set -euo pipefail

VERSION="${1:-v0.1.0}"
REPO="mainspring-labs/mainspring-contracts"
OUT="$(cd "$(dirname "$0")/.." && pwd)/src/spec.ts"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

gh release download "$VERSION" -R "$REPO" -D "$TMP" \
  -p mainspring_spring.wasm -p mainspring_factory.wasm -p SHA256SUMS
(cd "$TMP" && grep -E 'mainspring_(spring|factory)\.wasm' SHA256SUMS | sed 's/\*//' | sha256sum -c -)

spec() {
  stellar contract info interface --wasm "$TMP/$1" --output xdr-base64
}

cat > "$OUT" <<TS
// Generated by scripts/gen-spec.sh from $REPO $VERSION. Do not edit.

export const CONTRACTS_VERSION = "$VERSION";

export const SPRING_WASM_SHA256 =
  "$(grep mainspring_spring.wasm "$TMP/SHA256SUMS" | cut -d' ' -f1)";
export const FACTORY_WASM_SHA256 =
  "$(grep mainspring_factory.wasm "$TMP/SHA256SUMS" | cut -d' ' -f1)";

/** Base64 XDR stream of the spring contract's ScSpecEntry list. */
export const SPRING_SPEC = "$(spec mainspring_spring.wasm)";

/** Base64 XDR stream of the factory contract's ScSpecEntry list. */
export const FACTORY_SPEC = "$(spec mainspring_factory.wasm)";
TS
echo "wrote $OUT"
